'''
	Archivo de definición de constantes
'''

_LEARNING_RATE_MIN = 0.01
_LEARNING_RATE_MAX = 1
_LEARNING_RATE_STEP = 0.01

_DISCOUNT_MIN = 0
_DISCOUNT_MAX = 1
_DISCOUNT_STEP = 0.01

_EPSILON_MIN = 0
_EPSILON_MAX = 1
_EPSILON_STEP = 0.1

_LEARNING_EPSILON_MIN = 0.001
_LEARNING_EPSILON_MAX = 1
_LEARNING_EPSILON_STEP = 0.001

_MIN_EPSILON_MIN = 0.01
_MIN_EPSILON_MAX = 1
_MIN_EPSILON_STEP = 0.01

_MAX_MOVEMENTS_MIN = 2
_MAX_MOVEMENTS_MAX = 100
_MAX_MOVEMENTS_STEP = 1

_WIN_REWARD_MIN = -50
_WIN_REWARD_MAX = 50
_WIN_REWARD_STEP = 1

_LOSS_REWARD_MIN = -50
_LOSS_REWARD_MAX = 50
_LOSS_REWARD_STEP = 1

_DEAD_REWARD_MIN = -50
_DEAD_REWARD_MAX = 50
_DEAD_REWARD_STEP = 1

_LOOP_REWARD_MIN = -50
_LOOP_REWARD_MAX = 50
_LOOP_REWARD_STEP = 1

minimos = [
	_LEARNING_RATE_MIN, _DISCOUNT_MIN, _EPSILON_MIN, _LEARNING_EPSILON_MIN, _MIN_EPSILON_MIN, _MAX_MOVEMENTS_MIN, _WIN_REWARD_MIN, _LOSS_REWARD_MIN, _DEAD_REWARD_MIN, _LOOP_REWARD_MIN
]

maximos = [
	_LEARNING_RATE_MAX, _DISCOUNT_MAX, _EPSILON_MAX, _LEARNING_EPSILON_MAX, _MIN_EPSILON_MAX, _MAX_MOVEMENTS_MAX, _WIN_REWARD_MAX, _LOSS_REWARD_MAX, _DEAD_REWARD_MAX, _LOOP_REWARD_MAX 
]

steps = [
	_LEARNING_RATE_STEP, _DISCOUNT_STEP, _EPSILON_STEP, _LEARNING_EPSILON_STEP, _MIN_EPSILON_STEP, _MAX_MOVEMENTS_STEP, _WIN_REWARD_STEP, _LOSS_REWARD_STEP, _DEAD_REWARD_STEP, _LOOP_REWARD_STEP 
]